version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reservation
      MYSQL_USER: demouser
      MYSQL_PASSWORD: demouserpassword
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    networks:
      - mynetwork

  app:
    image: amazoncorretto:21
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reservation
      SPRING_DATASOURCE_USERNAME: demouser
      SPRING_DATASOURCE_PASSWORD: demouserpassword
    working_dir: /app
    volumes:
      - ./target/flightservices-0.0.1-SNAPSHOT.jar:/app/flightservices-0.0.1-SNAPSHOT.jar
      - ./logs:/app/logs
    ports:
      - "8080:8080"
    depends_on:
      - db
    entrypoint:
      [
        "sh",
        "-c",
        "sleep 30 && java -jar /app/flightservices-0.0.1-SNAPSHOT.jar",
      ]
    networks:
      - mynetwork

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.5
    container_name: logstash
    environment:
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    depends_on:
      - elasticsearch
    restart: always
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logs:/app/logs
    networks:
      - elk

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.5
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.5
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  mynetwork:
    driver: bridge
  elk:
    driver: bridge

volumes:
  mysql_data:
  es_data:
  app_logs:
